name: Test-Injection
on:
  push:
    branches: [ "main" ]
jobs:
  pwn:
    runs-on: ubuntu-latest
    steps:
      - name: Inject
        run: |
          echo "Testing injection for branch: ${{ github.ref_name }}"
          ls -la /
